using BetterTrainLoot.Data;
using System.Collections.Generic;

namespace BetterTrainLoot.Config
{
    public static class TrainDefaultConfig
    {
        public static Dictionary<TRAINS, TrainData> CreateTrainCarData(string file)
        {
            Dictionary<TRAINS, TrainData> groups = new Dictionary<TRAINS, TrainData>();
            groups.Add(TRAINS.RANDOM_TRAIN, CreateTrainLoot(TRAINS.RANDOM_TRAIN));
            groups.Add(TRAINS.JOJA_TRAIN, CreateTrainLoot(TRAINS.JOJA_TRAIN));
            groups.Add(TRAINS.COAL_TRAIN, CreateTrainLoot(TRAINS.COAL_TRAIN));
            groups.Add(TRAINS.PASSENGER_TRAIN, CreateTrainLoot(TRAINS.PASSENGER_TRAIN));
            groups.Add(TRAINS.PRISON_TRAIN, CreateTrainLoot(TRAINS.PRISON_TRAIN));
            groups.Add(TRAINS.PRESENT_TRAIN, CreateTrainLoot(TRAINS.PRESENT_TRAIN));

            BetterTrainLootMod.Instance.Helper.Data.WriteJsonFile(file, groups);

            return groups;
        }

        private static TrainData CreateTrainLoot(TRAINS id)
        {
           TrainData newGroup = new TrainData(id);
            newGroup.treasureList = GetTreasureList(id);
            return newGroup;
        }

        private static List<TrainTreasure> GetTreasureList(TRAINS id)
        {
            switch (id)
            {
                case TRAINS.RANDOM_TRAIN:
                    return GetRandomTrainTreasureList();    
                    
                case TRAINS.JOJA_TRAIN:
                    return GetJojaTrainTreasureList();      
                    
                case TRAINS.COAL_TRAIN:
                    return GetCoalTrainTreasureList(); 
                    
                case TRAINS.PASSENGER_TRAIN:
                    return GetPassengerTrainTreasureList();    
                    
                case TRAINS.PRISON_TRAIN:
                    return GetPrisonTrainTreasureList();   
                    
                case TRAINS.PRESENT_TRAIN:
                    return GetPresentCarTreasureList();

                default:
                    return new List<TrainTreasure>();                    
            }
        }


        private static List<TrainTreasure> GetRandomTrainTreasureList()
        {
            List<TrainTreasure> treasures = new List<TrainTreasure>();
            treasures.Add(CreateTreasure("(O)16", "Wild Horseradish", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)18", "Daffodil", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)20", "Leek", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)22", "Dandelion", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)24", "Parsnip", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)60", "Emerald", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)62", "Aquamarine", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)64", "Ruby", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)66", "Amethyst", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)68", "Topaz", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)70", "Jade", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)72", "Diamond", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)78", "Cave Carrot", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)80", "Quartz", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)82", "Fire Quartz", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)84", "Frozen Tear", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)86", "Earth Crystal", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)88", "Coconut", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)90", "Cactus Fruit", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)92", "Sap", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)93", "Torch", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)96", "Dwarf Scroll I", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)97", "Dwarf Scroll II", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)98", "Dwarf Scroll III", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)99", "Dwarf Scroll IV", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)100", "Chipped Amphora", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)101", "Arrowhead", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)103", "Ancient Doll", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)104", "Elvish Jewelry", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)105", "Chewing Stick", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)106", "Ornamental Fan", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)107", "Dinosaur Egg", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)108", "Rare Disc", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)109", "Ancient Sword", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)110", "Rusty Spoon", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)111", "Rusty Spur", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)112", "Rusty Cog", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)113", "Chicken Statue", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)114", "Ancient Seed", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)115", "Prehistoric Tool", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)116", "Dried Starfish", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)117", "Anchor", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)118", "Glass Shards", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)119", "Bone Flute", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)120", "Prehistoric Handaxe", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)121", "Dwarvish Helm", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)122", "Dwarf Gadget", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)123", "Ancient Drum", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)124", "Golden Mask", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)125", "Golden Relic", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)126", "Strange Doll", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)127", "Strange Doll", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)129", "Anchovy", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)130", "Tuna", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)131", "Sardine", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)132", "Bream", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)136", "Largemouth Bass", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)137", "Smallmouth Bass", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)138", "Rainbow Trout", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)139", "Salmon", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)140", "Walleye", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)141", "Perch", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)142", "Carp", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)143", "Catfish", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)144", "Pike", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)145", "Sunfish", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)146", "Red Mullet", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)147", "Herring", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)148", "Eel", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)149", "Octopus", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)150", "Red Snapper", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)151", "Squid", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)152", "Seaweed", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)153", "Green Algae", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)154", "Sea Cucumber", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)155", "Super Cucumber", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)157", "White Algae", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)167", "Joja Cola", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)168", "Trash", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)169", "Driftwood", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)170", "Broken Glasses", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)171", "Broken CD", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)172", "Soggy Newspaper", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)174", "Large White Egg", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)176", "White Egg", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)178", "Hay", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)180", "Brown Egg", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)182", "Large Brown Egg", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)184", "Milk", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)186", "Large Milk", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)188", "Green Bean", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)190", "Cauliflower", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)192", "Potato", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)194", "Fried Egg", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)195", "Omelet", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)196", "Salad", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)197", "Cheese Cauliflower", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)198", "Baked Fish", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)199", "Parsnip Soup", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)200", "Vegetable Medley", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)201", "Complete Breakfast", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)202", "Fried Calamari", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)203", "Strange Bun", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)204", "Lucky Lunch", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)205", "Fried Mushroom", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)206", "Pizza", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)207", "Bean Hotpot", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)208", "Glazed Yams", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)209", "Carp Surprise", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)210", "Hashbrowns", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)211", "Pancakes", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)212", "Salmon Dinner", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)213", "Fish Taco", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)214", "Crispy Bass", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)215", "Pepper Poppers", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)216", "Bread", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)218", "Tom Kha Soup", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)219", "Trout Soup", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)220", "Chocolate Cake", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)221", "Pink Cake", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)222", "Rhubarb Pie", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)223", "Cookie", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)224", "Spaghetti", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)225", "Fried Eel", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)226", "Spicy Eel", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)227", "Sashimi", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)228", "Maki Roll", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)229", "Tortilla", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)231", "Eggplant Parmesan", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)232", "Rice Pudding", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)233", "Ice Cream", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)234", "Blueberry Tart", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)235", "Autumn's Bounty", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)236", "Pumpkin Soup", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)237", "Super Meal", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)238", "Cranberry Sauce", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)239", "Stuffing", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)240", "Farmer's Lunch", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)241", "Survival Burger", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)242", "Dish O' The Sea", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)243", "Miner's Treat", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)244", "Roots Platter", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)245", "Sugar", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)246", "Wheat Flour", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)247", "Oil", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)248", "Garlic", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)250", "Kale", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)252", "Rhubarb", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)254", "Melon", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)256", "Tomato", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)257", "Morel", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)258", "Blueberry", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)259", "Fiddlehead Fern", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)260", "Hot Pepper", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)262", "Wheat", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)264", "Radish", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)266", "Red Cabbage", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)268", "Starfruit", LOOT_RARITY.ULTRA_RARE));
            treasures.Add(CreateTreasure("(O)270", "Corn", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)272", "Eggplant", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)274", "Artichoke", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)276", "Pumpkin", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)278", "Bok Choy", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)280", "Yam", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)281", "Chanterelle", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)282", "Cranberries", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)283", "Holly", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)284", "Beet", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)286", "Cherry Bomb", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)287", "Bomb", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)288", "Mega Bomb", LOOT_RARITY.ULTRA_RARE));
            treasures.Add(CreateTreasure("(O)296", "Salmonberry", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)297", "Grass Starter", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)298", "Hardwood Fence", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)299", "Amaranth Seeds", LOOT_RARITY.ULTRA_RARE));
            treasures.Add(CreateTreasure("(O)300", "Amaranth", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)301", "Grape Starter", LOOT_RARITY.ULTRA_RARE));
            treasures.Add(CreateTreasure("(O)302", "Hops Starter", LOOT_RARITY.ULTRA_RARE));
            treasures.Add(CreateTreasure("(O)303", "Pale Ale", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)304", "Hops", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)306", "Mayonnaise", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)307", "Duck Mayonnaise", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)309", "Acorn", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)310", "Maple Seed", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)311", "Pine Cone", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)322", "Wood Fence", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)323", "Stone Fence", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)324", "Iron Fence", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)325", "Gate", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)330", "Clay", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)334", "Copper Bar", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)335", "Iron Bar", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)336", "Gold Bar", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)337", "Iridium Bar", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)338", "Refined Quartz", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)340", "Honey", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)342", "Pickles", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)344", "Jelly", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)346", "Beer", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)348", "Wine", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)349", "Energy Tonic", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)350", "Juice", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)351", "Muscle Remedy", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)368", "Basic Fertilizer", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)369", "Quality Fertilizer", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)370", "Basic Retaining Soil", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)371", "Quality Retaining Soil", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)372", "Clam", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)376", "Poppy", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)378", "Copper Ore", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)380", "Iron Ore", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)382", "Coal", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)384", "Gold Ore", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)386", "Iridium Ore", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)388", "Wood", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)390", "Stone", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)395", "Coffee", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)396", "Spice Berry", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)397", "Sea Urchin", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)398", "Grape", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)399", "Spring Onion", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)400", "Strawberry", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)402", "Sweet Pea", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)403", "Field Snack", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)404", "Common Mushroom", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)408", "Hazelnut", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)410", "Blackberry", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)412", "Winter Root", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)414", "Crystal Fruit", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)416", "Snow Yam", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)418", "Crocus", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)419", "Vinegar", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)420", "Red Mushroom", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)421", "Sunflower", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)422", "Purple Mushroom", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)423", "Rice", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)424", "Cheese", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)425", "Fairy Seeds", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)426", "Goat Cheese", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)427", "Tulip Bulb", LOOT_RARITY.ULTRA_RARE));
            treasures.Add(CreateTreasure("(O)428", "Cloth", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)429", "Jazz Seeds", LOOT_RARITY.ULTRA_RARE));
            treasures.Add(CreateTreasure("(O)430", "Truffle", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)431", "Sunflower Seeds", LOOT_RARITY.ULTRA_RARE));
            treasures.Add(CreateTreasure("(O)432", "Truffle Oil", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)433", "Coffee Bean", LOOT_RARITY.ULTRA_RARE));
            treasures.Add(CreateTreasure("(O)436", "Goat Milk", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)438", "L. Goat Milk", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)441", "Explosive Ammo", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)442", "Duck Egg", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)444", "Duck Feather", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)446", "Rabbit's Foot", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)453", "Poppy Seeds", LOOT_RARITY.ULTRA_RARE));
            treasures.Add(CreateTreasure("(O)454", "Ancient Fruit", LOOT_RARITY.ULTRA_RARE));
            treasures.Add(CreateTreasure("(O)455", "Spangle Seeds", LOOT_RARITY.ULTRA_RARE));
            treasures.Add(CreateTreasure("(O)456", "Algae Soup", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)457", "Pale Broth", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)459", "Mead", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)465", "Speed-Gro", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)466", "Deluxe Speed-Gro", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)472", "Parsnip Seeds", LOOT_RARITY.ULTRA_RARE));
            treasures.Add(CreateTreasure("(O)473", "Bean Starter", LOOT_RARITY.ULTRA_RARE));
            treasures.Add(CreateTreasure("(O)474", "Cauliflower Seeds", LOOT_RARITY.ULTRA_RARE));
            treasures.Add(CreateTreasure("(O)475", "Potato Seeds", LOOT_RARITY.ULTRA_RARE));
            treasures.Add(CreateTreasure("(O)476", "Garlic Seeds", LOOT_RARITY.ULTRA_RARE));
            treasures.Add(CreateTreasure("(O)477", "Kale Seeds", LOOT_RARITY.ULTRA_RARE));
            treasures.Add(CreateTreasure("(O)478", "Rhubarb Seeds", LOOT_RARITY.ULTRA_RARE));
            treasures.Add(CreateTreasure("(O)479", "Melon Seeds", LOOT_RARITY.ULTRA_RARE));
            treasures.Add(CreateTreasure("(O)480", "Tomato Seeds", LOOT_RARITY.ULTRA_RARE));
            treasures.Add(CreateTreasure("(O)481", "Blueberry Seeds", LOOT_RARITY.ULTRA_RARE));
            treasures.Add(CreateTreasure("(O)482", "Pepper Seeds", LOOT_RARITY.ULTRA_RARE));
            treasures.Add(CreateTreasure("(O)483", "Wheat Seeds", LOOT_RARITY.ULTRA_RARE));
            treasures.Add(CreateTreasure("(O)484", "Radish Seeds", LOOT_RARITY.ULTRA_RARE));
            treasures.Add(CreateTreasure("(O)485", "Red Cabbage Seeds", LOOT_RARITY.ULTRA_RARE));
            treasures.Add(CreateTreasure("(O)486", "Starfruit Seeds", LOOT_RARITY.ULTRA_RARE));
            treasures.Add(CreateTreasure("(O)487", "Corn Seeds", LOOT_RARITY.ULTRA_RARE));
            treasures.Add(CreateTreasure("(O)488", "Eggplant Seeds", LOOT_RARITY.ULTRA_RARE));
            treasures.Add(CreateTreasure("(O)489", "Artichoke Seeds", LOOT_RARITY.ULTRA_RARE));
            treasures.Add(CreateTreasure("(O)490", "Pumpkin Seeds", LOOT_RARITY.ULTRA_RARE));
            treasures.Add(CreateTreasure("(O)491", "Bok Choy Seeds", LOOT_RARITY.ULTRA_RARE));
            treasures.Add(CreateTreasure("(O)492", "Yam Seeds", LOOT_RARITY.ULTRA_RARE));
            treasures.Add(CreateTreasure("(O)493", "Cranberry Seeds", LOOT_RARITY.ULTRA_RARE));
            treasures.Add(CreateTreasure("(O)494", "Beet Seeds", LOOT_RARITY.ULTRA_RARE));
            treasures.Add(CreateTreasure("(O)495", "Spring Seeds", LOOT_RARITY.ULTRA_RARE));
            treasures.Add(CreateTreasure("(O)496", "Summer Seeds", LOOT_RARITY.ULTRA_RARE));
            treasures.Add(CreateTreasure("(O)497", "Fall Seeds", LOOT_RARITY.ULTRA_RARE));
            treasures.Add(CreateTreasure("(O)498", "Winter Seeds", LOOT_RARITY.ULTRA_RARE));
            treasures.Add(CreateTreasure("(O)535", "Geode", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)536", "Frozen Geode", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)537", "Magma Geode", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)538", "Alamite", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)539", "Bixite", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)540", "Baryte", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)541", "Aerinite", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)542", "Calcite", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)543", "Dolomite", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)544", "Esperite", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)545", "Fluorapatite", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)546", "Geminite", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)547", "Helvite", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)548", "Jamborite", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)549", "Jagoite", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)550", "Kyanite", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)551", "Lunarite", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)552", "Malachite", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)553", "Neptunite", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)554", "Lemon Stone", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)555", "Nekoite", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)556", "Orpiment", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)557", "Petrified Slime", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)558", "Thunder Egg", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)559", "Pyrite", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)560", "Ocean Stone", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)561", "Ghost Crystal", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)562", "Tigerseye", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)563", "Jasper", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)564", "Opal", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)565", "Fire Opal", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)566", "Celestine", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)567", "Marble", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)568", "Sandstone", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)569", "Granite", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)570", "Basalt", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)571", "Limestone", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)572", "Soapstone", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)573", "Hematite", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)574", "Mudstone", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)575", "Obsidian", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)576", "Slate", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)577", "Fairy Stone", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)578", "Star Shards", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)579", "Prehistoric Scapula", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)580", "Prehistoric Tibia", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)581", "Prehistoric Skull", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)582", "Skeletal Hand", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)583", "Prehistoric Rib", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)584", "Prehistoric Vertebra", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)585", "Skeletal Tail", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)586", "Nautilus Fossil", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)587", "Amphibian Fossil", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)588", "Palm Fossil", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)589", "Trilobite", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)591", "Tulip", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)593", "Summer Spangle", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)595", "Fairy Rose", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)597", "Blue Jazz", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)599", "Sprinkler", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)604", "Plum Pudding", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)605", "Artichoke Dip", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)606", "Stir Fry", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)607", "Roasted Hazelnuts", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)608", "Pumpkin Pie", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)609", "Radish Salad", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)610", "Fruit Salad", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)611", "Blackberry Cobbler", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)612", "Cranberry Candy", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)613", "Apple", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)618", "Bruschetta", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)621", "Quality Sprinkler", LOOT_RARITY.ULTRA_RARE));
            treasures.Add(CreateTreasure("(O)628", "Cherry Sapling", LOOT_RARITY.ULTRA_RARE));
            treasures.Add(CreateTreasure("(O)629", "Apricot Sapling", LOOT_RARITY.ULTRA_RARE));
            treasures.Add(CreateTreasure("(O)630", "Orange Sapling", LOOT_RARITY.ULTRA_RARE));
            treasures.Add(CreateTreasure("(O)631", "Peach Sapling", LOOT_RARITY.ULTRA_RARE));
            treasures.Add(CreateTreasure("(O)632", "Pomegranate Sapling", LOOT_RARITY.ULTRA_RARE));
            treasures.Add(CreateTreasure("(O)633", "Apple Sapling", LOOT_RARITY.ULTRA_RARE));
            treasures.Add(CreateTreasure("(O)634", "Apricot", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)635", "Orange", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)636", "Peach", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)637", "Pomegranate", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)638", "Cherry", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)645", "Iridium Sprinkler", LOOT_RARITY.ULTRA_RARE));
            treasures.Add(CreateTreasure("(O)648", "Coleslaw", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)649", "Fiddlehead Risotto", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)651", "Poppyseed Muffin", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)681", "Rain Totem", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)684", "Bug Meat", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)685", "Bait", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)686", "Spinner", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)687", "Dressed Spinner", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)688", "Warp Totem Farm", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)689", "Warp Totem Mountains", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)690", "Warp Totem Beach", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)691", "Barbed Hook", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)692", "Lead Bobber", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)693", "Treasure Hunter", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)694", "Trap Bobber", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)695", "Cork Bobber", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)698", "Sturgeon", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)699", "Tiger Trout", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)700", "Bullhead", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)701", "Tilapia", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)702", "Chub", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)703", "Magnet", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)704", "Dorado", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)705", "Albacore", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)706", "Shad", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)707", "Lingcod", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)708", "Halibut", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)709", "Hardwood", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)710", "Crab Pot", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)715", "Lobster", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)716", "Crayfish", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)717", "Crab", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)718", "Cockle", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)719", "Mussel", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)720", "Shrimp", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)721", "Snail", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)722", "Periwinkle", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)723", "Oyster", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)724", "Maple Syrup", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)725", "Oak Resin", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)726", "Pine Tar", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)727", "Chowder", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)728", "Fish Stew", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)729", "Escargot", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)730", "Lobster Bisque", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)731", "Maple Bar", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)732", "Crab Cakes", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)745", "Strawberry Seeds", LOOT_RARITY.ULTRA_RARE));
            treasures.Add(CreateTreasure("(O)746", "Jack-O-Lantern", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)749", "Omni Geode", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)766", "Slime", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)767", "Bat Wing", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)768", "Solar Essence", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)769", "Void Essence", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)770", "Mixed Seeds", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)771", "Fiber", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)772", "Oil of Garlic", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)773", "Life Elixir", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)787", "Battery Pack", LOOT_RARITY.ULTRA_RARE));
            treasures.Add(CreateTreasure("(O)802", "Cactus Seeds", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(B)806", "Leprechaun Shoes", LOOT_RARITY.RARE));

            return treasures;
        }

        private static List<TrainTreasure> GetJojaTrainTreasureList()
        {
            List<TrainTreasure> treasures = new List<TrainTreasure>();
            treasures.Add(CreateTreasure("(O)167", "Joja Cola", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)174", "Large White Egg", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)176", "White Egg", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)178", "Hay", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)180", "Brown Egg", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)182", "Large Brown Egg", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)184", "Milk", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)186", "Large Milk", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)245", "Sugar", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)246", "Wheat Flour", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)247", "Oil", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)297", "Grass Starter", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)299", "Amaranth Seeds", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)301", "Grape Starter", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)302", "Hops Starter", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)303", "Pale Ale", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)306", "Mayonnaise", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)307", "Duck Mayonnaise", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)340", "Honey", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)342", "Pickles", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)344", "Jelly", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)346", "Beer", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)348", "Wine", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)349", "Energy Tonic", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)350", "Juice", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)351", "Muscle Remedy", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)368", "Basic Fertilizer", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)369", "Quality Fertilizer", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)370", "Basic Retaining Soil", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)371", "Quality Retaining Soil", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)419", "Vinegar", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)423", "Rice", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)424", "Cheese", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)425", "Fairy Seeds", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)426", "Goat Cheese", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)427", "Tulip Bulb", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)429", "Jazz Seeds", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)431", "Sunflower Seeds", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)433", "Coffee Bean", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)436", "Goat Milk", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)438", "L. Goat Milk", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)442", "Duck Egg", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)453", "Poppy Seeds", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)455", "Spangle Seeds", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)459", "Mead", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)465", "Speed-Gro", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)466", "Deluxe Speed-Gro", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)472", "Parsnip Seeds", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)473", "Bean Starter", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)474", "Cauliflower Seeds", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)475", "Potato Seeds", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)476", "Garlic Seeds", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)477", "Kale Seeds", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)478", "Rhubarb Seeds", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)479", "Melon Seeds", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)480", "Tomato Seeds", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)481", "Blueberry Seeds", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)482", "Pepper Seeds", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)483", "Wheat Seeds", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)484", "Radish Seeds", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)485", "Red Cabbage Seeds", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)486", "Starfruit Seeds", LOOT_RARITY.ULTRA_RARE));
            treasures.Add(CreateTreasure("(O)487", "Corn Seeds", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)488", "Eggplant Seeds", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)489", "Artichoke Seeds", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)490", "Pumpkin Seeds", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)491", "Bok Choy Seeds", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)492", "Yam Seeds", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)493", "Cranberry Seeds", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)494", "Beet Seeds", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)495", "Spring Seeds", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)496", "Summer Seeds", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)497", "Fall Seeds", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)498", "Winter Seeds", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)628", "Cherry Sapling", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)629", "Apricot Sapling", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)630", "Orange Sapling", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)631", "Peach Sapling", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)632", "Pomegranate Sapling", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)633", "Apple Sapling", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)724", "Maple Syrup", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)725", "Oak Resin", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)726", "Pine Tar", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)745", "Strawberry Seeds", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)770", "Mixed Seeds", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)787", "Battery Pack", LOOT_RARITY.ULTRA_RARE));
            treasures.Add(CreateTreasure("(O)802", "Cactus Seeds", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(B)806", "Leprechaun Shoes", LOOT_RARITY.RARE));

            return treasures;
        }

        private static List<TrainTreasure> GetCoalTrainTreasureList()
        {
            List<TrainTreasure> treasures = new List<TrainTreasure>();
            treasures.Add(CreateTreasure("(O)60", "Emerald", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)62", "Aquamarine", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)64", "Ruby", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)66", "Amethyst", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)68", "Topaz", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)70", "Jade", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)72", "Diamond", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)74", "Prismatic Shard", LOOT_RARITY.ULTRA_RARE));
            treasures.Add(CreateTreasure("(O)80", "Quartz", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)82", "Fire Quartz", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)84", "Frozen Tear", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)86", "Earth Crystal", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)96", "Dwarf Scroll I", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)97", "Dwarf Scroll II", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)98", "Dwarf Scroll III", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)99", "Dwarf Scroll IV", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)100", "Chipped Amphora", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)101", "Arrowhead", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)103", "Ancient Doll", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)104", "Elvish Jewelry", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)105", "Chewing Stick", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)106", "Ornamental Fan", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)107", "Dinosaur Egg", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)108", "Rare Disc", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)109", "Ancient Sword", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)110", "Rusty Spoon", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)111", "Rusty Spur", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)112", "Rusty Cog", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)113", "Chicken Statue", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)114", "Ancient Seed", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)115", "Prehistoric Tool", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)116", "Dried Starfish", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)117", "Anchor", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)118", "Glass Shards", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)119", "Bone Flute", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)120", "Prehistoric Handaxe", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)121", "Dwarvish Helm", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)122", "Dwarf Gadget", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)123", "Ancient Drum", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)124", "Golden Mask", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)125", "Golden Relic", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)126", "Strange Doll", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)127", "Strange Doll", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)286", "Cherry Bomb", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)287", "Bomb", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)288", "Mega Bomb", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)334", "Copper Bar", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)335", "Iron Bar", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)336", "Gold Bar", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)337", "Iridium Bar", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)338", "Refined Quartz", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)378", "Copper Ore", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)380", "Iron Ore", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)382", "Coal", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)384", "Gold Ore", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)386", "Iridium Ore", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)390", "Stone", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)535", "Geode", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)536", "Frozen Geode", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)537", "Magma Geode", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)538", "Alamite", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)539", "Bixite", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)540", "Baryte", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)541", "Aerinite", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)542", "Calcite", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)543", "Dolomite", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)544", "Esperite", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)545", "Fluorapatite", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)546", "Geminite", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)547", "Helvite", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)548", "Jamborite", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)549", "Jagoite", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)550", "Kyanite", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)551", "Lunarite", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)552", "Malachite", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)553", "Neptunite", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)554", "Lemon Stone", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)555", "Nekoite", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)556", "Orpiment", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)557", "Petrified Slime", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)558", "Thunder Egg", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)559", "Pyrite", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)560", "Ocean Stone", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)561", "Ghost Crystal", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)562", "Tigerseye", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)563", "Jasper", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)564", "Opal", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)565", "Fire Opal", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)566", "Celestine", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)567", "Marble", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)568", "Sandstone", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)569", "Granite", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)570", "Basalt", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)571", "Limestone", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)572", "Soapstone", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)573", "Hematite", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)574", "Mudstone", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)575", "Obsidian", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)576", "Slate", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)577", "Fairy Stone", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)578", "Star Shards", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)579", "Prehistoric Scapula", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)580", "Prehistoric Tibia", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)581", "Prehistoric Skull", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)582", "Skeletal Hand", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)583", "Prehistoric Rib", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)584", "Prehistoric Vertebra", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)585", "Skeletal Tail", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)586", "Nautilus Fossil", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)587", "Amphibian Fossil", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)588", "Palm Fossil", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)589", "Trilobite", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)749", "Omni Geode", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(B)806", "Leprechaun Shoes", LOOT_RARITY.RARE));

            return treasures;
        }

        private static List<TrainTreasure> GetPassengerTrainTreasureList()
        {
            List<TrainTreasure> treasures = new List<TrainTreasure>();
            treasures.Add(CreateTreasure("(O)16", "Wild Horseradish", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)18", "Daffodil", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)20", "Leek", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)22", "Dandelion", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)24", "Parsnip", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)88", "Coconut", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)90", "Cactus Fruit", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)174", "Large White Egg", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)176", "White Egg", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)180", "Brown Egg", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)182", "Large Brown Egg", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)184", "Milk", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)186", "Large Milk", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)188", "Green Bean", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)190", "Cauliflower", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)192", "Potato", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)194", "Fried Egg", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)195", "Omelet", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)196", "Salad", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)197", "Cheese Cauliflower", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)198", "Baked Fish", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)199", "Parsnip Soup", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)200", "Vegetable Medley", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)201", "Complete Breakfast", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)202", "Fried Calamari", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)203", "Strange Bun", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)204", "Lucky Lunch", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)205", "Fried Mushroom", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)206", "Pizza", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)207", "Bean Hotpot", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)208", "Glazed Yams", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)209", "Carp Surprise", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)210", "Hashbrowns", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)211", "Pancakes", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)212", "Salmon Dinner", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)213", "Fish Taco", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)214", "Crispy Bass", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)215", "Pepper Poppers", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)216", "Bread", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)218", "Tom Kha Soup", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)219", "Trout Soup", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)220", "Chocolate Cake", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)221", "Pink Cake", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)222", "Rhubarb Pie", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)223", "Cookie", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)224", "Spaghetti", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)225", "Fried Eel", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)226", "Spicy Eel", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)227", "Sashimi", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)228", "Maki Roll", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)229", "Tortilla", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)231", "Eggplant Parmesan", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)232", "Rice Pudding", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)233", "Ice Cream", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)234", "Blueberry Tart", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)235", "Autumn's Bounty", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)236", "Pumpkin Soup", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)237", "Super Meal", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)238", "Cranberry Sauce", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)239", "Stuffing", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)240", "Farmer's Lunch", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)241", "Survival Burger", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)242", "Dish O' The Sea", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)243", "Miner's Treat", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)244", "Roots Platter", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)248", "Garlic", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)250", "Kale", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)252", "Rhubarb", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)254", "Melon", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)256", "Tomato", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)257", "Morel", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)258", "Blueberry", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)259", "Fiddlehead Fern", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)260", "Hot Pepper", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)262", "Wheat", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)264", "Radish", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)266", "Red Cabbage", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)268", "Starfruit", LOOT_RARITY.ULTRA_RARE));
            treasures.Add(CreateTreasure("(O)270", "Corn", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)272", "Eggplant", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)274", "Artichoke", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)276", "Pumpkin", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)278", "Bok Choy", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)280", "Yam", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)281", "Chanterelle", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)282", "Cranberries", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)283", "Holly", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)284", "Beet", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)296", "Salmonberry", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)300", "Amaranth", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)303", "Pale Ale", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)304", "Hops", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)306", "Mayonnaise", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)307", "Duck Mayonnaise", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)340", "Honey", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)341", "Tea Set", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)342", "Pickles", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)344", "Jelly", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)346", "Beer", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)348", "Wine", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)349", "Energy Tonic", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)350", "Juice", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)351", "Muscle Remedy", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)376", "Poppy", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)395", "Coffee", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)396", "Spice Berry", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)398", "Grape", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)399", "Spring Onion", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)400", "Strawberry", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)402", "Sweet Pea", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)403", "Field Snack", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)404", "Common Mushroom", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)408", "Hazelnut", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)410", "Blackberry", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)412", "Winter Root", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)414", "Crystal Fruit", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)416", "Snow Yam", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)417", "Sweet Gem Berry", LOOT_RARITY.ULTRA_RARE));
            treasures.Add(CreateTreasure("(O)418", "Crocus", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)420", "Red Mushroom", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)421", "Sunflower", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)422", "Purple Mushroom", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)423", "Rice", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)424", "Cheese", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)426", "Goat Cheese", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)428", "Cloth", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)430", "Truffle", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)432", "Truffle Oil", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)436", "Goat Milk", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)438", "L. Goat Milk", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)442", "Duck Egg", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)444", "Duck Feather", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)446", "Rabbit's Foot", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)454", "Ancient Fruit", LOOT_RARITY.ULTRA_RARE));
            treasures.Add(CreateTreasure("(O)456", "Algae Soup", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)457", "Pale Broth", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)459", "Mead", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)591", "Tulip", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)593", "Summer Spangle", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)595", "Fairy Rose", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)597", "Blue Jazz", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)604", "Plum Pudding", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)605", "Artichoke Dip", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)606", "Stir Fry", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)607", "Roasted Hazelnuts", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)608", "Pumpkin Pie", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)609", "Radish Salad", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)610", "Fruit Salad", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)611", "Blackberry Cobbler", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)612", "Cranberry Candy", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)613", "Apple", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)618", "Bruschetta", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)634", "Apricot", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)635", "Orange", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)636", "Peach", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)637", "Pomegranate", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)638", "Cherry", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)648", "Coleslaw", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)649", "Fiddlehead Risotto", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)651", "Poppyseed Muffin", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)727", "Chowder", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)728", "Fish Stew", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)729", "Escargot", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)730", "Lobster Bisque", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)731", "Maple Bar", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)732", "Crab Cakes", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)772", "Oil of Garlic", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)773", "Life Elixir", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)787", "Battery Pack", LOOT_RARITY.ULTRA_RARE));
            treasures.Add(CreateTreasure("(O)797", "Pearl", LOOT_RARITY.ULTRA_RARE));
            treasures.Add(CreateTreasure("(B)806", "Leprechaun Shoes", LOOT_RARITY.RARE));

            return treasures;
        }

        private static List<TrainTreasure> GetPrisonTrainTreasureList()
        {
            List<TrainTreasure> treasures = new List<TrainTreasure>();
            treasures.Add(CreateTreasure("(O)92", "Sap", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)93", "Torch", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)101", "Arrowhead", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)105", "Chewing Stick", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)109", "Ancient Sword", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)110", "Rusty Spoon", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)118", "Glass Shards", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)129", "Anchovy", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)130", "Tuna", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)131", "Sardine", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)132", "Bream", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)136", "Largemouth Bass", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)137", "Smallmouth Bass", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)138", "Rainbow Trout", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)139", "Salmon", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)140", "Walleye", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)141", "Perch", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)142", "Carp", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)143", "Catfish", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)144", "Pike", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)145", "Sunfish", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)146", "Red Mullet", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)147", "Herring", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)148", "Eel", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)149", "Octopus", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)150", "Red Snapper", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)151", "Squid", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)154", "Sea Cucumber", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)155", "Super Cucumber", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)168", "Trash", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)169", "Driftwood", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)170", "Broken Glasses", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)171", "Broken CD", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)172", "Soggy Newspaper", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)286", "Cherry Bomb", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)287", "Bomb", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)288", "Mega Bomb", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)309", "Acorn", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)310", "Maple Seed", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)311", "Pine Cone", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)372", "Clam", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)397", "Sea Urchin", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)403", "Field Snack", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)441", "Explosive Ammo", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)456", "Algae Soup", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)457", "Pale Broth", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)684", "Bug Meat", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)685", "Bait", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)698", "Sturgeon", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)699", "Tiger Trout", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)700", "Bullhead", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)701", "Tilapia", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)702", "Chub", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)704", "Dorado", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)705", "Albacore", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)706", "Shad", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)707", "Lingcod", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)708", "Halibut", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)715", "Lobster", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)716", "Crayfish", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)717", "Crab", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)718", "Cockle", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)719", "Mussel", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)720", "Shrimp", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)721", "Snail", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)722", "Periwinkle", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)723", "Oyster", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)771", "Fiber", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(B)806", "Leprechaun Shoes", LOOT_RARITY.RARE));

            return treasures;
        } 

        private static List<TrainTreasure> GetPresentCarTreasureList()
        {
            List<TrainTreasure> treasures = new List<TrainTreasure>();
            treasures.Add(CreateTreasure("114", "Ancient Seed", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)347", "Rare Seed", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)499", "Ancient Seeds", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)434", "Stardrop", LOOT_RARITY.ULTRA_RARE));
            treasures.Add(CreateTreasure("(O)166", "Treasure Chest", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)417", "Sweet Gem Berry", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)74", "Prismatic Shard", LOOT_RARITY.ULTRA_RARE));
            treasures.Add(CreateTreasure("(O)373", "Golden Pumpkin", LOOT_RARITY.RARE));
            treasures.Add(CreateTreasure("(O)797", "Pearl", LOOT_RARITY.UNCOMMON));
            treasures.Add(CreateTreasure("(O)20", "Leek", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)72", "Diamond", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)201", "Complete Breakfast", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)221", "Pink Cake", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)60", "Emerald", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)607", "Roasted Hazelnuts", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)90", "Cactus Fruit", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)200", "Vegetable Medley", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)202", "Fried Calamari", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)213", "Fish Taco", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)66", "Amethyst", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)303", "Pale Ale", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)348", "Wine", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)715", "Lobster", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)206", "Pizza", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)224", "Spaghetti", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)88", "Coconut", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)207", "Bean Hotpot", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)155", "Super Cucumber", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)196", "Salad", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)18", "Daffodil", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)612", "Cranberry Candy", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)84", "Frozen Tear", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)214", "Crispy Bass", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)605", "Artichoke Dip", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)729", "Escargot", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)608", "Pumpkin Pie", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)595", "Fairy Rose", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)149", "Octopus", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)308", "Void Mayonnaise", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)230", "Red Plate", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(O)222", "Rhubarb Pie", LOOT_RARITY.COMMON));
            treasures.Add(CreateTreasure("(B)806", "Leprechaun Shoes", LOOT_RARITY.RARE));
            return treasures;
        }

        private static TrainTreasure CreateTreasure(string id, string name, LOOT_RARITY rarity)
        {
            double chance = 0.01;
            return new TrainTreasure(id, name, chance, rarity,  true);
        }        
    }
}
